### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by calebkrauter**
Implement specifications for credits, resources and how to use. Upon completing the Readme.md as a team in merge we should reopen this [PR](https://github.com/GoodBadChad/good-bad-chad-br/pull/68#issue-2092713924) so that our main branch is up to date.

### CODE REVIEW

**Review by b1gd3vd0g — APPROVED** [review]
Looks good! Includes more relevant information. Should we not include more than just "Web game" though? I think the overview we had, or another one, would still be appropriate so people know what kind of game to expect.

**Comment by calebkrauter** [comment]
> Looks good! Includes more relevant information. Should we not include more than just "Web game" though? I think the overview we had, or another one, would still be appropriate so people know what kind of game to expect.

Good idea! I took another look at what you wrote in the previous README regarding the journey and I like it! I'll add it to the README in its own section keeping it organized.

**Review by calebkrauter — COMMENTED** [review]
Updated README based on @B1GD3VD0G's suggestion.
Thanks!

**Review by tclaar — APPROVED** [review]
Looks good! Thanks for adding this info.

**Pull request merged**
